// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8791' | (string & {});
};

/**
 * Person
 */
export type Person = {
    /**
     * Name
     */
    name: string;
    /**
     * Age
     */
    age: number;
};

export type TestRouteV1TestGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/test';
};

export type TestRouteV1TestGetResponses = {
    /**
     * Successful Response
     */
    200: Person;
};

export type TestRouteV1TestGetResponse = TestRouteV1TestGetResponses[keyof TestRouteV1TestGetResponses];
